// This is an autogenerated file from Firebase Studio.
'use server';
/**
 * @fileOverview A flow to provide recommendations on how to optimize Average Order Value (AOV).
 *
 * - optimizeAOV - A function that handles the AOV optimization process.
 * - OptimizeAOVInput - The input type for the optimizeAOV function.
 * - OptimizeAOVOutput - The return type for the optimizeAOV function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const OptimizeAOVInputSchema = z.object({
  storeName: z.string().describe('The name of the store.'),
  averageOrderValue: z.number().describe('The current average order value.'),
  products: z.array(z.object({
    name: z.string().describe('The name of the product.'),
    price: z.number().describe('The price of the product.'),
    salesLastMonth: z.number().describe('The number of sales of the product in the last month.'),
  })).describe('A list of products in the store with their price and sales data.'),
});
export type OptimizeAOVInput = z.infer<typeof OptimizeAOVInputSchema>;

const OptimizeAOVOutputSchema = z.object({
  recommendations: z.array(z.string()).describe('A list of recommendations to optimize the average order value.'),
  expectedImpact: z.string().describe('The expected impact of the recommendations on the average order value.'),
});
export type OptimizeAOVOutput = z.infer<typeof OptimizeAOVOutputSchema>;

export async function optimizeAOV(input: OptimizeAOVInput): Promise<OptimizeAOVOutput> {
  return optimizeAOVFlow(input);
}

const prompt = ai.definePrompt({
  name: 'optimizeAOVPrompt',
  input: {schema: OptimizeAOVInputSchema},
  output: {schema: OptimizeAOVOutputSchema},
  prompt: `You are an expert in e-commerce and marketing. Your goal is to provide recommendations to store owners on how to optimize their Average Order Value (AOV).

  The store name is: {{{storeName}}}
  The current AOV is: {{{averageOrderValue}}}

  Here is a list of products in the store, along with their price and sales data:
  {{#each products}}
  - Name: {{{name}}}, Price: {{{price}}}, Sales Last Month: {{{salesLastMonth}}}
  {{/each}}

  Based on this information, provide a list of recommendations to optimize the AOV and an estimate of the expected impact.
  The recommendations should be specific and actionable. Consider strategies such as bundling products, offering discounts for larger orders, and suggesting complementary products.
  The expected impact should be a brief explanation of how the recommendations will affect the AOV and overall revenue.
  Make sure the output is valid JSON.
  `,
});

const optimizeAOVFlow = ai.defineFlow(
  {
    name: 'optimizeAOVFlow',
    inputSchema: OptimizeAOVInputSchema,
    outputSchema: OptimizeAOVOutputSchema,
  },
  async input => {
    const {output} = await prompt(input);
    return output!;
  }
);
